name: PHPUnit

on:
  - push
  - pull_request

jobs:
  phpunit:
    name: "PHP 7.4 (windows-latest)"
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: intl
          tools: ""
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: Execute
        run: |
          vendor/bin/phpunit
