name: PHPUnit

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  settings:
    name: Collect settings
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.value }}
      extensions: ${{ steps.extensions.outputs.value }}
      dependencies: ${{ steps.dependencies.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: echo "$GITHUB_EVENT_NAME"
      - run: echo "$(if [ ! "$GITHUB_EVENT_NAME" == "schedule" ]; then echo "lowest"; fi)"
      - name: Detect dependencies versions
        id: dependencies
        run: |
          DEPS_HIGHEST="highest"
          DEPS_LOCKED="$(if [ -f "composer.lock" ] && [ ! "$GITHUB_EVENT_NAME" == "schedule" ]; then echo "locked"; fi)"
          DEPS_LOWEST="$(if [ ! "$GITHUB_EVENT_NAME" == "schedule" ]; then echo "lowest"; fi)"
          echo "::set-output name=value::$(echo "[\"$DEPS_HIGHEST\", \"$DEPS_LOCKED\", \"$DEPS_LOWEST\"]" | jq "[.[] | select(length > 0)]" -r -c)"
      - name: Detect PHP versions
        id: versions
        run: |
          mkdir "$RUNNER_TEMP/easy-ci"
          composer require --no-interaction --working-dir="$RUNNER_TEMP/easy-ci" --update-no-dev symplify/easy-ci
          echo "::set-output name=value::$("$RUNNER_TEMP/easy-ci/vendor/bin/easy-ci" php-versions-json)"
      - name: Detect PHP extensions
        id: extensions
        run: |
          echo "::set-output name=value::$(jq '[.require, ."require-dev", .suggest] | add | to_entries | map(select(.key | match("ext-";"i"))) | map(.key | sub("ext-"; "")) | join(", ")' -r -c composer.json)"

  phpunit:
    name: "Output"

    runs-on: ubuntu-latest
    needs:
      - settings

    steps:
      - run: echo "${{ needs.settings.outputs.versions }}"
      - run: echo "${{ needs.settings.outputs.extensions }}"
      - run: echo "${{ needs.settings.outputs.dependencies }}"
